### ISSUE TITLE
 build之后，运行失败

### ISSUE THREAD

**Issue by zspishere** [Harhao/electron-vite-react-starter#1]
Hi，您的这个项目很赞！
我在build过程中，遇到一个问题，麻烦帮忙确认是我操作的问题，还是代码存在bug。

# 错误描述
`yarn build`之后，采用以下两种方式运行，均`显示白框`，`Developer Tools`报错如下

![白框](https://user-images.githubusercontent.com/19356426/120947208-8a45e380-c771-11eb-8291-986a9f1c9541.png)

![Developer Tools报错](https://user-images.githubusercontent.com/19356426/120947130-59fe4500-c771-11eb-9727-d2e6d583ff98.png)

# 错误复现
- 直接运行unpacked软件：`electron-vite-react-starter\release\0.0.1\win-unpacked\electron-vite-react-starter.exe`
- 本地安装之后，再运行安装之后的软件。安装程序：`electron-vite-react-starter\release\0.0.1\electron-vite-react-starter_0.0.1.exe`

**Comment by Harhao** [comment]
@zspishere 你好，感谢你提的意见，这边是由于`vite.config.ts `配置文件中的配置输入目录写错了

1. 把`renderer`写成了`render`,所以最后打包结果寻址出错。

现在这个问题已经修复，谢谢你的喜欢和意见
